# Concluzii

În urma analizei noastre concluzionăm următoarele lucruri despre România: avem un mediu economic relativ precar, în mare parte axat pe comerț, industrie prelucrătoare și construcții, posibil bântuit de evaziune fiscală și muncă la negru, cu o cantitate mică de capital (bogăție) acumulat relativ la țările vestice, cu aproximativ jumătate din firme nefiind capabile de a obține vreun profit, mai ales cele care sunt îndatorate peste măsură (capital negativ). Nici firmele cu capital pozitiv nu stau foarte bine, un sfert din ele nereușind să obțină, de asemenea, profituri. Profitabilitatea măsurată ca procent din cifra de afaceri sau din active este bună pentru cele care obțin așa ceva, atât la nivel național cât și în diferite sectoare, dar este un procent mare din sume derizorii. Doar 30 % din firme au un venit lunar din profit echivalent cu un salariu bun. E mare nevoie de o anchetă țintită din partea ANAF, făcută pe baze de metodologie științifică (randomizat de preferință) pentru a nu irosi multe resurse umane și financiare și să ne permită să estimăm cu suficientă siguranță gradul și amploarea evaziunii fiscale. Ca și cum problema nu era destul de rea, teoreticienii și economiștii pesediști au împins în mod repetat pentru coborârea pragului de impozitare pentru microîntreprinderi, astfel că 96 % din firmele din țară au ajuns clasificate în acest fel, lucru care contribuie la și mai puțin impozit colectat la un buget de stat și așa precar. Ar fi mare nevoie de acces la datele de la Registrul Comerțului pentru a analiza aceste date și în funcție de originea națională a capitalului. În lipsa acestor lucruri sunt slabe șanse să obținem resursele de care avem nevoie pentru a construi o economie mai performantă și majoritatea discuțiilor economice vor rămâne pe tărâmul teoreticului sau, mai rău, al speculativului.   

